### ISSUE TITLE
アイコンを変更できるようにする

### ISSUE THREAD

**Issue by Sottiki** [team-ful/noratomo#26]

**Comment by cateiru** [comment]
[仕様]

- Google Cloud Storageを使用する？
  - ローカルでじっこうする際にはエミュレータを動かす？
  - https://github.com/fsouza/fake-gcs-server とか？
  - Amd64対応していないとPiで動かせない
    - https://hub.docker.com/r/fsouza/fake-gcs-server/tags 
    - 対応してそう OK

[TODO]

- [ ] https://github.com/fsouza/fake-gcs-server を動かす`docker-compose`追加する
- [ ] cloud storageのconfig書く
- [ ] ラップクラスとテスト書く
- [ ] 画像アップロード、削除、変更のメソッドを追加する
