### ISSUE TITLE
トップページ

### ISSUE THREAD

**Issue by cateiru** [team-ful/noratomo#83]
## 概要

パス`/`のページ。野良友がどういうものであるかといった紹介があると良さそう。

ログインしてこのページにアクセスすると`/dashbord`か`/home`にリダイレクトするためアカウントを作成していない人を対象にしたページにしたい。

## 他のサイト例

- Twitter
  
  ![image](https://user-images.githubusercontent.com/24271196/175780438-99ac8498-f610-4f76-a43e-f921bfb27db9.png)
  https://twitter.com/

- dアニメストア

  ![image](https://user-images.githubusercontent.com/24271196/175780507-b16d68a7-0fd7-41c1-93a7-bb6b73f0dcd0.png)
  https://animestore.docomo.ne.jp/animestore/tp_pc

- Netflix

  ![image](https://user-images.githubusercontent.com/24271196/175780519-22ea5e0b-b79a-4254-92b5-e9cbeea2ffe4.png)
  https://www.netflix.com/jp/

**Comment by Sottiki** [comment]
タップルのページとか良かったよ

**Comment by cateiru** [comment]
@Sottiki フルページスクリーンショットで貼ってもらえると良さそう
